version: '2'

services:

  nameindexer:
    image: bioatlas/backbone:v0.1
    command: /bin/ash

  api: 
    image: dina/classifications-api:v0.1
    ports:
      - "8080:8080"
    volumes_from:
      - nameindexer
    container_name: api

  backup:
    image: alpine
    command: /bin/ash
    volumes:
      - ./backups:/tmp/
    volumes_from:
      - nameindexer
